### ISSUE TITLE
.Net Core Load failed

### ISSUE THREAD

**Issue by micah686** [Nikey646/VndbSharp#13]
I'm not sure if this is an issue with your code, or with my IDE, but visual studio 2015 gives me a "load failed" when loading the .net core .sln solution, both for VndbConsoleCore and VndbSharp.

Was there something you had to enable to work on a .net core project?

**Comment by Nikey646** [comment]
The project is built using Visual Studio 2017. The project.json format has been discontinued in the latest version of .Net Core and is automatically upgraded to the new .csproj format.

It also has some sparse usage of C#7 through out the project(s), which Visual Studio 2015 doesn't understand (And might not even be able to compile).

**Comment by micah686** [comment]
Ah, so I'd need to be on visual studio 2017 RC to use it?

**Comment by Nikey646** [comment]
Yup. RC3 is the version i'm using at this point in time.
