### ISSUE TITLE
[Bug] Broken Visual Novel Relationship Type

### ISSUE THREAD

**Issue by micah686** [Nikey646/VndbSharp#28]
The Relationship type only and ALWAYS returns the first value in the Enum, rather than going through the members as it should. So right now, whenever you try to get the relations of a novel, it will ONLY return Sequel, since that is at the top of the Enum. 
Switching the top value changes what is returned, so it's obviously reading the top values. 
I also checked against the results of vndb, and made sure that VndbSharp was returning incorrect values, which it was.

**Comment by Nikey646** [comment]
Let me know if the commit fixed it.

Also, god damnit github, i didn't want to close this issue

**Comment by micah686** [comment]
Nope, it's still broken.

**Comment by Nikey646** [comment]
Okay, i'll have to give it a proper look to see whats going wrong later, when i get a break away from another project.
