### ISSUE TITLE
[Bug] Attempting to run a GetVisualNovelAsync() now crashes

### ISSUE THREAD

**Issue by micah686** [Nikey646/VndbSharp#29]
When attempting to run a GetVisualNovelAsync(), the program.cs crashes.

Exception: Newtonsoft.Json.JsonSerializationException: 'Error setting value to 'Type' on 'VndbSharp.Models.VisualNovel.VisualNovelRelation'.'

Inner Exception: NullReferenceException: Object reference not set to an instance of an object.

I KNOW this used to work, so I think one of the latest commits broke it.

**Comment by Nikey646** [comment]
Do you know when i sleep or something? You always seem to make an issue that can quickly be resolved when i sleep <__<

**Comment by micah686** [comment]
I just am working on a code using your api late at night. That's probably why.
