### ISSUE TITLE
[Feature Request] Add support for the latest API changes

### ISSUE THREAD

**Issue by micah686** [Nikey646/VndbSharp#32]
There have been some new updates to the [Vndb API](https://vndb.org/d11#8). Could you add support for these new features please?

2017-06-21
-  Add "resolution", "voiced", "animation" members to "get release" command
-    Add "platforms" filter to "get release" command
-   Accept arrays for the "vn" filter to the "get release" command
-    Add "search" filter to "get staff"

**Comment by Nikey646** [comment]
Should be resolved in https://github.com/Nikey646/VndbSharp/commit/d403feaf59c241debf482b450092733e8b35f372, lemme know if there are any problems.

**Comment by micah686** [comment]
Ok, everything seems to work properly now.

On a side note, why haven't you merged Features/GetStaff into master yet?

**Comment by Nikey646** [comment]
Because i haven't gotten around to fully testing it myself, or writing the example method in the Console project(s).
