### ISSUE TITLE
Error when using VndbFilers.Username.Equals("")

### ISSUE THREAD

**Issue by micah686** [Nikey646/VndbSharp#36]
Whenever I try to use the filter VndbFilters.Username.Equals(""), it outputs an error.

So if I do something like:
`var result = await client.GetVisualNovelListAsync(VndbFilters.Username.Equals("micah686"));`, the console will output:
```
get vnlist basic (username="micah686")
Get Response | error {"id":"filter","msg":"Unknown field 'username'","op":"=","value":"micah686","field":"username"}
{"id":"filter","msg":"Unknown field 'username'","op":"=","value":"micah686","field":"username"}
```

This only happens for the Username filter. The UserId filter works just fine.

**Comment by Nikey646** [comment]
The username filter is not valid for the [Get VNList](https://vndb.org/d11#5.8) endpoint. It's only used on [Get User](https://vndb.org/d11#5.6).

**Comment by micah686** [comment]
Oh, whoops. I totally missed that.
