### ISSUE TITLE
Add support for voiced in "get character"

### ISSUE THREAD

**Issue by micah686** [Nikey646/VndbSharp#45]
It doesn't seem like there is support for the voiced option for characters in this project. I looked over the API briefly, and I didn't see any reference to it.

**Comment by Nikey646** [comment]
It would appear to have been missed, somehow. Woops.

Next time i work on the code, i'll make sure to add it.

**Comment by Nikey646** [comment]
Fixed in #49, not sure when i'll merge it to be honest.
